### ISSUE TITLE
Loop in uth.controller.js

### ISSUE THREAD

**Issue by Vallejoanderson** [Mail-On-Bike/MoB-Hermes#19]
Según la Documentación de la W3C:

Fuente: 
https://www.w3.org/wiki/JavaScript_best_practices#Optimize_loops

Puedo crear una nueva rama y compararlas en un PR.

          // Revisando las autoridades
          const authorities = [];
          const roles = await user.getRoles();
```diff 
-      for (let i = 0; i < roles.length; i++) {
+      for (let i = 0, j = roles.length; i < j; i++) {
        authorities.push(roles[i].name.toUpperCase());
      }
      user.roles = authorities;

      // Creando el token
      const token = jwt.sign({ data: user }, config.secret, {
        expiresIn: 2592000, // 30 días
      });

**Comment by RageHardrack** [comment]
Muy buena observación y aporte. Revisaré esos loops siguiendo la doc de W3C. También tenía en mente cambiar el clásico `for` por `for of`.

**Comment by RageHardrack** [comment]
Agradecido con tus observaciones @Vallejoanderson.
Ha sido buen aporte y he refactorizado el código, aunque no siguiendo tu consejo, sino que opté por usar `for of`.

Antes:
```js
for (let i = 0; i < roles.length; i++) {
... roles[i].name ...
}
```
Ahora:
```js
for(let rol of roles) {
... rol.name ...
}
```

Si esto tampoco es buena práctica, me lo harás saber jaja.
